In [1]:
'''
numpy is also denoted as []
'''

'\nnumpy is also denoted as []\n'

In [2]:
import numpy as np

In [3]:
a = [1,2,3,4]
b = [5,6,7,8]
c = a + b
print(c)
#concatenated output, list are concatenated in python,so we need numpy to perform the operation

[1, 2, 3, 4, 5, 6, 7, 8]


In [4]:
a_num = np.array(a)
b_num = np.array(b)

In [5]:
print(a_num)
print(b_num)

[1 2 3 4]
[5 6 7 8]


In [9]:
a_num + b_num

array([ 6,  8, 10, 12])

In [7]:
type(a_num)

numpy.ndarray

In [10]:
# 2D array
array_2d = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
array_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
'''
    slicing used for data extraction.
    2d slicing
    ----

    mainly used in machine learning
array_2d[row slice, column slice]
'''



'\n    slicing used for data extraction.\n    2d slicing\n    ----\n\n    mainly used in machine learning\narray_2d[row slice, column slice]\n'

In [12]:
array_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
array_2d[1:,1:]

array([[5, 6],
       [8, 9]])

In [14]:
a_num = np.array([1,2,3,4])
b_num = np.array([3,4,5,6,7,8])
a_num + b_num # broadcast error

ValueError: operands could not be broadcast together with shapes (4,) (6,) 

### shape,size,ndim

In [18]:
array_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
array_2d.shape

(3, 3)

In [17]:
array_2d.size

9

In [20]:
array_2d.ndim

2

### zeros and ones

In [22]:
zeros_1 = np.zeros(6,dtype="int")
zeros_1

array([0, 0, 0, 0, 0, 0])

In [23]:
ones_1 = np.ones(6,dtype="int")
ones_1

array([1, 1, 1, 1, 1, 1])

In [26]:
zeros_2 = np.zeros((3,10),dtype = int)
zeros_2

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [27]:
ones_2 = np.ones((3,10),dtype=int)
ones_2

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

## time is 10:36am,

## arange

In [30]:
numbers = np.arange(1,61)
numbers

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60])

## reshape and Ravel
- Gives a new shape to an array without changing its data.

In [33]:
reshape_numbers = numbers.reshape(6,10)
reshape_numbers

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60]])

In [35]:
ravel_number = np.ravel(reshape_numbers)
ravel_number

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60])

- to plot the images in the graph, sometimes we have to convert to one dimensional so we need ravel
- If learning ML-> it is called flatten()

### homework: array broadcasting, boolean indexing